### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by CodyGramlich** [github-tools/github#549]
npm audit gives
```
found 46 vulnerabilities (21 low, 19 moderate, 5 high, 1 critical) in 6373 scanned packages
  39 vulnerabilities require semver-major dependency updates.
  7 vulnerabilities require manual review. See the full report for details.
```

The one critical vulnerability is 
```
  Critical        Command Injection
  Package         growl
  Dependency of   mocha [dev]
  Path            mocha > growl
  More info       https://nodesecurity.io/advisories/146
```
This requires growl to be greater than version 1.10.2, which requires mocha to be at least 4.0.1. Currently mocha 3.1.2 is being used.

**Comment by CodyGramlich** [comment]
Upgrading gulp from 3.9.0 to 4.0.0 solves 6 vulnerabilities, but then `gulp build` no longer works and gives me this error:
```
[17:18:53] Requiring external module babel-register
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\codgra1\Documents\Projects\github\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\codgra1\Documents\Projects\github\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:/Users/codgra1/Documents/Projects/github/gulpfile.babel.js:31:6)
    at Module._compile (module.js:653:30)
    at loader (C:\Users\codgra1\Documents\Projects\github\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\codgra1\Documents\Projects\github\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```
