### ISSUE TITLE
Creating search from string doesn't work

### ISSUE THREAD

**Issue by Heath123** [github-tools/github#642]
Trying to use the function http://github-tools.github.io/github/docs/3.2.3/GitHub.html#search (using 3.4.0 but the docs aren't up for that) like this:
```js
console.log(gh.search('query'))
```
gives this error:
```
/home/heath/SyncedProjects/CredentialReminderBot/node_modules/github-api/dist/components/Requestable.js:162
            requestOptions.type = requestOptions.type || 'all';
                                ^

TypeError: Cannot create property 'type' on string 'query'
    at Search._getOptionsWithDefaults (/home/heath/SyncedProjects/CredentialReminderBot/node_modules/github-api/dist/components/Requestable.js:162:33)
    at new Search (/home/heath/SyncedProjects/CredentialReminderBot/node_modules/github-api/dist/components/Search.js:46:30)
    at GitHub.search (/home/heath/SyncedProjects/CredentialReminderBot/node_modules/github-api/dist/components/GitHub.js:159:14)
    at Object.<anonymous> (/home/heath/SyncedProjects/CredentialReminderBot/index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Heath123** [comment]
Looks like it actually needs this, not a string:
` @param {Object} [requestOptions={}] - the current options for the request`

**Comment by Heath123** [comment]
There's also no `forCommits` on the class

**Comment by Heath123** [comment]
```json
data: {
      message: "If you would like to help us test the Commit Search API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.",
      documentation_url: 'https://docs.github.com/rest/reference/search#search-commits'
}
```
Huh, I guess I'll have to do that part manually?

**Comment by Heath123** [comment]
```js
data: {
      message: "API rate limit exceeded for 95.111.249.143. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
      documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
}
```
Is this my fault or is auth broken?

**Comment by Heath123** [comment]
```js
const search = gh.search({ q: 'query' })
search.__AcceptHeader = 'cloak-preview'
console.log(search)
search._search('commits', { q: 'query' }, (test, test2) => { console.log(test, test2) })
```
This seems to work
