### ISSUE TITLE
I am getting errors

### ISSUE THREAD

**Issue by adhvaithprasad** [github-tools/github#654]
Hey I am getting a ton of errors
```
Promise { <pending> }
Hint: hit control+c anytime to enter REPL.
(node:378) UnhandledPromiseRejectionWarning: Error: 401 error making request post https://api.github.com/gists: "Unauthorized"
    at new ResponseError (/home/runner/SomberColossalRam/node_modules/github-api/dist/components/Requestable.js:50:118)
    at handler (/home/runner/SomberColossalRam/node_modules/github-api/dist/components/Requestable.js:379:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by adhvaithprasad** [comment]
I am sure I entered the correct password and username
