### ISSUE TITLE
jar包启动，本地虚拟机，正常启动，云服务器启动报错！

### ISSUE THREAD

**Issue by mygithub-one** [github-tools/github#662]

**Comment by mygithub-one** [comment]
> ```
> 14:03:41.000 logback [xxl-job, admin JobScheduleHelper#scheduleThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>> init xxl-job admin scheduler success.
> 14:04:12.200 logback [xxl-job, admin JobRegistryMonitorHelper-registryMonitorThread] ERROR com.zaxxer.hikari.pool.HikariPool - HikariCP - Exception during pool initialization.
> java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
> 	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903)
> 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
> 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
> 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
> 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
> 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
> 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
> 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
> 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
> 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
> 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
> 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
> 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
> 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
> 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
> 	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
> 	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
> 	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
> 	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
> 	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
> 	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
> 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
> 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
> 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
> 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
> 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
> 	at com.sun.proxy.$Proxy72.selectList(Unknown Source)
> 	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
> 	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
> 	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
> 	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
> 	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
> 	at com.sun.proxy.$Proxy73.findByAddressType(Unknown Source)
> 	at com.xxl.job.admin.core.thread.JobRegistryHelper$3.run(JobRegistryHelper.java:62)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
> ```
